-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 09:19:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exmachinis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exmachinis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exmachinis` DEFAULT CHARACTER SET utf8 ;
USE `exmachinis` ;

-- -----------------------------------------------------
-- Table `exmachinis`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exmachinis`.`users` ;

CREATE TABLE IF NOT EXISTS `exmachinis`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `exmachinis`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exmachinis`.`companies` ;

CREATE TABLE IF NOT EXISTS `exmachinis`.`companies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `companies_name_unique` (`name` ASC) VISIBLE,
  INDEX `companies_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `companies_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `exmachinis`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `exmachinis`.`agents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exmachinis`.`agents` ;

CREATE TABLE IF NOT EXISTS `exmachinis`.`agents` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `company_id` INT(10) UNSIGNED NOT NULL,
  `coord_x` DOUBLE(8,2) NOT NULL,
  `coord_y` DOUBLE(8,2) NOT NULL,
  `coord_z` DOUBLE(8,2) NOT NULL,
  `speed_x` DOUBLE(8,2) NOT NULL DEFAULT '0.00',
  `speed_y` DOUBLE(8,2) NOT NULL DEFAULT '0.00',
  `speed_z` DOUBLE(8,2) NOT NULL DEFAULT '0.00',
  `vm` MEDIUMBLOB NULL DEFAULT NULL,
  `input` LONGTEXT NULL DEFAULT NULL,
  `output` LONGTEXT NULL DEFAULT NULL,
  `subject` VARCHAR(2048) NULL DEFAULT NULL,
  `object_id` INT(11) NOT NULL DEFAULT '187',
  PRIMARY KEY (`id`),
  INDEX `agents_company_id_foreign` (`company_id` ASC) VISIBLE,
  CONSTRAINT `agents_company_id_foreign`
    FOREIGN KEY (`company_id`)
    REFERENCES `exmachinis`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `exmachinis`.`commands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exmachinis`.`commands` ;

CREATE TABLE IF NOT EXISTS `exmachinis`.`commands` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(2048) NOT NULL,
  `agent_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `subject` VARCHAR(2048) NULL DEFAULT NULL,
  `email_content` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `commands_agent_id_foreign` (`agent_id` ASC) VISIBLE,
  CONSTRAINT `commands_agent_id_foreign`
    FOREIGN KEY (`agent_id`)
    REFERENCES `exmachinis`.`agents` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1438522
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `exmachinis`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exmachinis`.`migrations` ;

CREATE TABLE IF NOT EXISTS `exmachinis`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `exmachinis`.`objects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exmachinis`.`objects` ;

CREATE TABLE IF NOT EXISTS `exmachinis`.`objects` (
  `object_id` INT(11) NOT NULL,
  `object_name` VARCHAR(45) NOT NULL,
  `object_type` VARCHAR(16) NOT NULL,
  `gravitational_parameter` DOUBLE NULL DEFAULT NULL,
  `central_body_object_id` INT(11) NULL DEFAULT NULL,
  `epoch` DATETIME NULL DEFAULT NULL,
  `semimajor_axis` DOUBLE NULL DEFAULT NULL,
  `eccentricity` DECIMAL(10,9) NULL DEFAULT NULL,
  `periapsis_argument` DECIMAL(12,9) NULL DEFAULT NULL,
  `mean_anomaly` DECIMAL(12,9) NULL DEFAULT NULL,
  `inclination` DECIMAL(12,9) NULL DEFAULT NULL,
  `ascending_node_longitude` DECIMAL(12,9) NULL DEFAULT NULL,
  `mean_angular_motion` DECIMAL(13,9) NULL DEFAULT NULL,
  PRIMARY KEY (`object_id`),
  UNIQUE INDEX `object_id_UNIQUE` (`object_id` ASC) VISIBLE,
  UNIQUE INDEX `object_name_UNIQUE` (`object_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `exmachinis`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exmachinis`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `exmachinis`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
