-- MySQL Script generated by MySQL Workbench
-- Tue Dec  4 15:49:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exmachinis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exmachinis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exmachinis` DEFAULT CHARACTER SET utf8 ;
USE `exmachinis` ;

-- -----------------------------------------------------
-- Table `exmachinis`.`objects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exmachinis`.`objects` ;

CREATE TABLE IF NOT EXISTS `exmachinis`.`objects` (
  `object_id` INT NOT NULL,
  `object_name` VARCHAR(45) NOT NULL,
  `object_type` VARCHAR(16) NOT NULL,
  `gravitational_parameter` DOUBLE NULL,
  `central_body_object_id` INT NULL,
  `epoch` DATETIME NULL,
  `semimajor_axis` DOUBLE NULL,
  `eccentricity` DECIMAL(10,9) NULL,
  `periapsis_argument` DECIMAL(12,9) NULL,
  `mean_anomaly` DECIMAL(12,9) NULL,
  `inclination` DECIMAL(12,9) NULL,
  `ascending_node_longitude` DECIMAL(12,9) NULL,
  `mean_angular_motion` DECIMAL(13,9) NULL,
  PRIMARY KEY (`object_id`),
  UNIQUE INDEX `object_id_UNIQUE` (`object_id` ASC),
  UNIQUE INDEX `object_name_UNIQUE` (`object_name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `exmachinis`.`objects`
-- -----------------------------------------------------
START TRANSACTION;
USE `exmachinis`;
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (0, 'Sun', 'Star', 1.33E+20, NULL, STR_TO_DATE
('1/1/1960', '%d/%m/%Y'), NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (1, 'Mercury', 'Planet', 2.20E+13, 0, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 0.00E+00, 0.20563593, 77.45779628, 252.2503235, 7.00497902, 48.33076593, 4.09205133);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (2, 'Venus', 'Planet', 3.25E+14, 0, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 0.00E+00, 0.00677672, 131.6024672, 181.9790995, 3.39467605, 76.67984255, 1.602008394);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (3, 'Earth', 'Planet', 3.99E+14, 0, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 0.00E+00, 0.01671123, 102.9376819, 100.4645717, -0.00001531, 0, 0.985536926);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (4, 'Mars', 'Planet', 4.28E+13, 0, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 0.00E+00, 0.0933941, -23.94362959, -4.55343205, 1.84969142, 49.55953891, 0.523987563);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (5, 'Jupiter', 'Planet', 1.27E+17, 0, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 0.00E+00, 0.04838624, 14.72847983, 34.39644051, 1.30439695, 100.4739091, 0.083043952);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (6, 'Saturn', 'Planet', 3.79E+16, 0, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 0.00E+00, 0.05386179, 92.59887831, 49.95424423, 2.48599187, 113.6624245, 0.033464093);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (7, 'Uranus', 'Planet', 5.79E+15, 0, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 0.00E+00, 0.04725744, 170.9542763, 313.2381045, 0.77263783, 74.01692503, 0.011724397);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (8, 'Neptune', 'Planet', 6.84E+15, 0, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 0.00E+00, 0.00859048, 44.96476227, -55.12002969, 1.77004347, 131.7842257, 0.005976902);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (9, 'Pluto', 'Planet', 8.71E+11, 0, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 0.00E+00, 0.2488273, 224.0689163, 238.9290383, 17.14001206, 110.3039368, 0.003972592);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (10, 'Moon', 'Moon', NULL, 3, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 3.84E+05, 0.0554, 318.15, 135.27, 5.16, 125.08, 13.176358);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (11, 'Phobos', 'Moon', NULL, 4, STR_TO_DATE
('01/01/1950', '%d/%m/%Y'), 9.38E+03, 0.0151, 150.057, 91.059, 1.075, 207.784, 1128.844757);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (12, 'Deimos', 'Moon', NULL, 4, STR_TO_DATE
('01/01/1950', '%d/%m/%Y'), 2.35E+04, 0.0002, 260.729, 325.329, 1.788, 24.525, 285.161879);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (13, 'Io', 'Moon', NULL, 5, STR_TO_DATE
('16/01/1997', '%d/%m/%Y'), 4.22E+05, 0.0041, 84.129, 342.021, 0.036, 43.977, 203.4889583);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (14, 'Europa', 'Moon', NULL, 5, STR_TO_DATE
('16/01/1997', '%d/%m/%Y'), 6.71E+05, 0.0094, 88.97, 171.016, 0.466, 219.106, 101.3747242);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (15, 'Ganymede', 'Moon', NULL, 5, STR_TO_DATE
('16/01/1997', '%d/%m/%Y'), 1.07E+06, 0.0013, 192.417, 317.54, 0.177, 63.552, 50.3176072);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (16, 'Callisto', 'Moon', NULL, 5, STR_TO_DATE
('16/01/1997', '%d/%m/%Y'), 1.88E+06, 0.0074, 52.643, 181.408, 0.192, 298.848, 21.5710728);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (17, 'Amalthea', 'Moon', NULL, 5, STR_TO_DATE
('16/01/1997', '%d/%m/%Y'), 1.81E+05, 0.0032, 155.873, 185.194, 0.38, 108.946, 722.6317143);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (18, 'Thebe', 'Moon', NULL, 5, STR_TO_DATE
('16/01/1997', '%d/%m/%Y'), 2.22E+05, 0.0176, 234.269, 135.956, 1.08, 235.694, 533.7002568);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (19, 'Adrastea', 'Moon', NULL, 5, STR_TO_DATE
('16/01/1997', '%d/%m/%Y'), 1.29E+05, 0.0018, 328.047, 135.673, 0.054, 228.378, 1206.998806);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (20, 'Metis', 'Moon', NULL, 5, STR_TO_DATE
('16/01/1997', '%d/%m/%Y'), 1.28E+05, 0.0012, 297.177, 276.047, 0.019, 146.912, 1221.254598);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (21, 'Himalia', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.15E+07, 0.1586, 331.234, 66.874, 28.612, 64.798, 1.4367562);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (22, 'Elara', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.17E+07, 0.2108, 142.001, 330.985, 27.945, 115.511, 1.3865315);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (23, 'Pasiphae', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.36E+07, 0.4062, 169.226, 279.769, 151.413, 314.223, 0.4841223);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (24, 'Sinope', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.39E+07, 0.2552, 354.541, 165.352, 158.189, 309.199, 0.4743772);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (25, 'Lysithea', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.17E+07, 0.1161, 49.67, 330.475, 27.663, 5.326, 1.3888891);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (26, 'Carme', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.34E+07, 0.2546, 26.416, 233.375, 164.994, 114.854, 0.4903501);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (27, 'Ananke', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.13E+07, 0.2332, 95.772, 253.384, 148.693, 15.959, 0.5716125);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (28, 'Leda', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.12E+07, 0.1624, 269.393, 230.352, 27.882, 219.181, 1.4942407);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (29, 'Callirrhoe', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.41E+07, 0.2796, 23.909, 107.962, 147.08, 283.104, 0.4744232);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (30, 'Themisto', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 7.50E+06, 0.2435, 217.147, 313.051, 42.977, 192.288, 2.7688033);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (31, 'Megaclite', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.38E+07, 0.4156, 288.882, 135.272, 152.781, 280.575, 0.4781658);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (32, 'Taygete', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.34E+07, 0.2523, 231.54, 94.756, 165.253, 305.114, 0.4915209);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (33, 'Chaldene', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.32E+07, 0.2503, 243.878, 267.454, 165.155, 134.24, 0.4974208);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (34, 'Harpalyke', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.11E+07, 0.2296, 134.505, 215.956, 148.759, 29.834, 0.5775515);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (35, 'Kalyke', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.36E+07, 0.2466, 218.934, 255.702, 165.121, 43.864, 0.485149);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (36, 'Iocaste', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.13E+07, 0.2152, 64.727, 213.675, 149.411, 269.613, 0.5699784);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (37, 'Erinome', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.33E+07, 0.2655, 10.274, 267.136, 164.914, 317.497, 0.4941719);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (38, 'Isonoe', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.32E+07, 0.2471, 116.879, 124.941, 165.25, 130.961, 0.4956884);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (39, 'Praxidike', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.11E+07, 0.2274, 190.862, 117.48, 148.885, 280.956, 0.5756381);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (40, 'Autonoe', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.40E+07, 0.3152, 54.793, 142.035, 152.364, 272.817, 0.4730563);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (41, 'Thyone', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.12E+07, 0.2307, 97.023, 238.786, 148.595, 233.022, 0.5739872);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (42, 'Hermippe', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.13E+07, 0.2095, 300.836, 131.854, 150.74, 330.393, 0.567904);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (43, 'Aitne', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.33E+07, 0.2627, 99.401, 105, 165.048, 8.679, 0.4930702);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (44, 'Eurydome', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.31E+07, 0.2755, 223.631, 287.689, 150.271, 302.47, 0.5018735);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (45, 'Euanthe', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.10E+07, 0.232, 320.635, 333.101, 148.915, 254.297, 0.5802269);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (46, 'Euporie', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.93E+07, 0.1438, 89.904, 70.243, 145.74, 60.143, 0.6537221);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (47, 'Orthosie', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.12E+07, 0.2807, 216.805, 204.517, 146.004, 221.949, 0.5782402);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (48, 'Sponde', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.38E+07, 0.3112, 61.885, 174.044, 150.997, 116.363, 0.481076);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (49, 'Kale', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.33E+07, 0.2597, 44.233, 212.853, 164.944, 60.17, 0.4934152);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (50, 'Pasithee', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.31E+07, 0.2682, 231.92, 215.443, 165.117, 327.729, 0.5003695);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (51, 'Hegemone', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.36E+07, 0.3445, 197.144, 236.95, 154.164, 318.902, 0.4866038);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (52, 'Mneme', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.10E+07, 0.2258, 40.542, 256.86, 148.585, 13.467, 0.5806001);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (53, 'Aoede', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.40E+07, 0.4325, 59.739, 197.676, 158.272, 173.392, 0.4728089);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (54, 'Thelxinoe', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.12E+07, 0.2201, 313.183, 268.013, 151.39, 169.962, 0.5732248);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (55, 'Arche', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.34E+07, 0.2495, 171.632, 39.713, 165.015, 339.21, 0.4918707);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (56, 'Kallichore', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.33E+07, 0.2509, 9.836, 55.937, 165.102, 30.339, 0.4943462);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (57, 'Helike', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.11E+07, 0.1498, 299.482, 43.659, 154.842, 89.749, 0.5747808);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (58, 'Carpo', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.71E+07, 0.4317, 90.372, 337.062, 51.624, 50.597, 0.7889862);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (59, 'Eukelade', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.33E+07, 0.2619, 309.685, 204.846, 165.265, 193.558, 0.492926);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (60, 'Cyllene', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.38E+07, 0.4155, 187.429, 128.345, 150.336, 252.611, 0.4787365);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (61, 'Kore', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.45E+07, 0.3313, 138.071, 33.416, 145.173, 313.355, 0.4634134);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (62, 'Herse', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.34E+07, 0.2541, 330.295, 141.667, 164.964, 295.702, 0.4901154);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (63, 'S/2000 J 11', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.23E+07, 0.232, 173.544, 309.734, 28.631, 294.497, 1.2939791);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (64, 'S/2003 J 2', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.83E+07, 0.41, 165.201, 237.932, 157.291, 344.782, 0.3671484);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (65, 'S/2003 J 3', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.02E+07, 0.1969, 66.338, 311.78, 147.547, 231.489, 0.6165779);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (66, 'S/2003 J 4', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.39E+07, 0.3624, 197.401, 260.48, 149.589, 179.131, 0.4766663);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (67, 'S/2003 J 5', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.35E+07, 0.2476, 90.066, 336.636, 165.248, 176.683, 0.4873118);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (68, 'S/2003 J 9', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.34E+07, 0.2632, 292.662, 348.415, 165.047, 44.321, 0.4909185);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (69, 'S/2003 J 10', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.30E+07, 0.4299, 170.833, 258.937, 165.073, 151.911, 0.5026172);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (70, 'S/2003 J 12', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.78E+07, 0.4904, 13.288, 38.543, 151.003, 65.53, 0.735186);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (71, 'S/2003 J 15', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.26E+07, 0.1899, 18.405, 58.865, 146.492, 236.674, 0.5219082);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (72, 'S/2003 J 16', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.11E+07, 0.2281, 57.681, 307.563, 148.683, 16.883, 0.5779589);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (73, 'S/2003 J 18', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.05E+07, 0.0895, 130.894, 202.16, 146.077, 158.247, 0.6018719);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (74, 'S/2003 J 19', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.35E+07, 0.2552, 176.668, 223.035, 165.116, 27.442, 0.4862156);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (75, 'S/2003 J 23', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.36E+07, 0.2746, 255.114, 144.222, 146.424, 41.706, 0.4914942);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (76, 'S/2010 J 1', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.34E+07, 0.2491, 189.23, 160.525, 165.1, 282.871, 0.4887995);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (77, 'S/2010 J 2', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.10E+07, 0.2267, 18.252, 312.074, 148.673, 5.802, 0.5817371);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (78, 'S/2011 J 1', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.34E+07, 0.2534, 31.514, 256.027, 165.318, 250.728, 0.4888998);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (79, 'S/2011 J 2', 'Moon', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.31E+07, 0.3493, 270.154, 285.597, 153.597, 24.866, 0.5011321);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (80, 'Mimas', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.86E+05, 0.0196, 332.499, 14.848, 1.574, 173.027, 381.9944948);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (81, 'Enceladus', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.38E+05, 0, 0.076, 199.686, 0.003, 342.507, 262.7318978);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (82, 'Tethys', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.95E+05, 0.0001, 45.202, 243.367, 1.091, 259.842, 190.6979109);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (83, 'Dione', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 3.77E+05, 0.0022, 284.315, 322.232, 0.028, 290.415, 131.5349307);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (84, 'Rhea', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 5.27E+05, 0.0002, 241.619, 179.781, 0.333, 351.042, 79.6900459);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (85, 'Titan', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.22E+06, 0.0288, 180.532, 163.31, 0.306, 28.06, 22.5769756);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (86, 'Hyperion', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.50E+06, 0.0232, 303.178, 86.342, 0.615, 263.847, 16.9199503);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (87, 'Iapetus', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 3.56E+06, 0.0293, 271.606, 201.789, 8.298, 81.105, 4.5379416);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (88, 'Phoebe', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.29E+07, 0.1634, 342.5, 53.038, 175.243, 241.086, 0.6569114);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (89, 'Janus', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.51E+05, 0.0098, 16.012, 17.342, 0.165, 154.175, 518.3431513);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (90, 'Epimetheus', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.51E+05, 0.0161, 88.975, 80.377, 0.353, 192.762, 518.0979676);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (91, 'Helene', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 3.77E+05, 0, 33.134, 43.186, 0.213, 163.112, 131.5349306);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (92, 'Telesto', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.95E+05, 0.0002, 119.135, 260.157, 1.18, 229.182, 190.6979089);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (93, 'Calypso', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.95E+05, 0.0005, 17.47, 156.66, 1.5, 314.226, 190.6979089);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (94, 'Atlas', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.38E+05, 0.0011, 210.851, 283.282, 0.003, 236.422, 598.3147505);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (95, 'Prometheus', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.39E+05, 0.0022, 37.514, 96.886, 0.007, 319.176, 587.2860142);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (96, 'Pandora', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.42E+05, 0.0042, 66.248, 125.112, 0.05, 147.272, 572.7878754);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (97, 'Pan', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.34E+05, 0, 103.331, 351.187, 0, 52.076, 626.0317341);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (98, 'Methone', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.94E+05, 0, 134.636, 71.189, 0.013, 313.562, 356.5949252);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (99, 'Pallene', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.12E+05, 0.004, 16.074, 356.229, 0.001, 123.18, 312.0270737);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (100, 'Polydeuces', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 3.77E+05, 0.0191, 311.847, 89.307, 0.175, 67.936, 131.5349306);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (101, 'Daphnis', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.37E+05, 0, 266.931, 113.79, 0.003, 132.867, 605.9791512);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (102, 'Anthe', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.97E+05, 0.0011, 138.902, 190.473, 0.015, 287.852, 347.3587167);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (103, 'Aegaeon', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.67E+05, 0.0002, 152.905, 322.771, 0.001, 317.202, 445.4934177);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (104, 'Ymir', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.31E+07, 0.3338, 21.352, 228.673, 173.497, 192.937, 0.2737369);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (105, 'Paaliaq', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.52E+07, 0.3325, 237.522, 321.654, 46.228, 330.022, 0.5240567);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (106, 'Tarvos', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.82E+07, 0.5382, 274.104, 265.783, 33.725, 102.504, 0.3886226);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (107, 'Ijiraq', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.14E+07, 0.2717, 92.899, 17.328, 47.485, 130.779, 0.7974868);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (108, 'Suttungr', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.95E+07, 0.1139, 34.281, 321.133, 175.815, 227.259, 0.3540952);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (109, 'Kiviuq', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.14E+07, 0.3325, 90.205, 172.018, 46.764, 353.584, 0.8013951);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (110, 'Mundilfari', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.87E+07, 0.2097, 309.694, 92.821, 167.439, 82.856, 0.3778328);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (111, 'Albiorix', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.64E+07, 0.4797, 55.932, 32.828, 34.06, 102.512, 0.4595027);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (112, 'Skathi', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.56E+07, 0.2718, 203.517, 114.689, 152.633, 286.599, 0.4944382);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (113, 'Erriapus', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.76E+07, 0.4722, 282.522, 294.829, 34.481, 150.985, 0.4132539);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (114, 'Siarnaq', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.82E+07, 0.2802, 65.929, 201.288, 45.809, 47.826, 0.4020067);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (115, 'Thrymr', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.04E+07, 0.4659, 125.404, 30.075, 177.659, 285.762, 0.3296678);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (116, 'Narvi', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.93E+07, 0.4296, 169.959, 114.172, 145.731, 174.435, 0.3585873);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (117, 'Aegir', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.08E+07, 0.2524, 242.651, 26.017, 166.668, 179.064, 0.3220526);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (118, 'Bebhionn', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.71E+07, 0.4682, 358.141, 168.045, 35.101, 199.128, 0.4312114);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (119, 'Bergelmir', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.93E+07, 0.142, 133.4, 306.494, 158.557, 202.164, 0.3579396);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (120, 'Bestla', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.02E+07, 0.5145, 81.185, 239.156, 145.136, 288.308, 0.3308757);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (121, 'Farbauti', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.04E+07, 0.2414, 342.995, 282.813, 156.52, 135.109, 0.3312924);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (122, 'Fenrir', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.25E+07, 0.1347, 120.982, 131.678, 164.963, 226.595, 0.2856343);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (123, 'Fornjot', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.51E+07, 0.2077, 324.787, 214.499, 170.372, 259.946, 0.2409497);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (124, 'Hati', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.99E+07, 0.371, 21.286, 163.64, 165.808, 324.38, 0.3460954);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (125, 'Hyrrokkin', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.84E+07, 0.3359, 273.076, 291.841, 151.536, 45.402, 0.3863203);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (126, 'Kari', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.21E+07, 0.4756, 163.935, 286.021, 156.067, 281.211, 0.2924012);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (127, 'Loge', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.31E+07, 0.1862, 32.821, 337.237, 167.689, 343.811, 0.2745228);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (128, 'Skoll', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.77E+07, 0.4636, 193.115, 44.965, 161.01, 296.623, 0.409912);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (129, 'Surtur', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.29E+07, 0.4459, 303.662, 136.191, 169.688, 236.537, 0.2775384);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (130, 'Jarnsaxa', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.94E+07, 0.2178, 237.422, 198.75, 163.649, 22.519, 0.3575194);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (131, 'Greip', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.85E+07, 0.3146, 152.16, 314.541, 174.8, 349.35, 0.3841491);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (132, 'Tarqeq', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.80E+07, 0.1675, 34.767, 161.02, 46.291, 83.291, 0.4067094);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (133, 'S/2004 S 7', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.10E+07, 0.529, 84.036, 79.762, 165.693, 341.236, 0.3157314);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (134, 'S/2004 S 12', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.99E+07, 0.3268, 87.128, 1.599, 165.261, 307.942, 0.3441326);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (135, 'S/2004 S 13', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.84E+07, 0.2591, 346.186, 41.077, 168.798, 205.701, 0.3856043);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (136, 'S/2004 S 17', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.94E+07, 0.1795, 180.792, 228.545, 168.239, 26.664, 0.3548169);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (137, 'S/2006 S 1', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.88E+07, 0.1412, 154.95, 96.596, 156.18, 336.641, 0.3741294);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (138, 'S/2006 S 3', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.24E+07, 0.3792, 188.728, 167.147, 158.631, 206.993, 0.2868177);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (139, 'S/2007 S 2', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.67E+07, 0.1791, 57.72, 84.066, 174.057, 111.277, 0.4454603);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (140, 'S/2007 S 3', 'Moon', NULL, 6, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.89E+07, 0.1853, 111.854, 292.691, 177.595, 276.824, 0.3681825);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (141, 'Ariel', 'Moon', NULL, 7, STR_TO_DATE
('01/01/1980', '%d/%m/%Y'), 1.91E+05, 0.0012, 115.349, 39.481, 0.041, 22.394, 142.8356579);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (142, 'Umbriel', 'Moon', NULL, 7, STR_TO_DATE
('01/01/1980', '%d/%m/%Y'), 2.66E+05, 0.0039, 84.709, 12.469, 0.128, 33.485, 86.8688879);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (143, 'Titania', 'Moon', NULL, 7, STR_TO_DATE
('01/01/1980', '%d/%m/%Y'), 4.36E+05, 0.0011, 284.4, 24.614, 0.079, 99.771, 41.3514246);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (144, 'Oberon', 'Moon', NULL, 7, STR_TO_DATE
('01/01/1980', '%d/%m/%Y'), 5.84E+05, 0.0014, 104.4, 283.088, 0.068, 279.771, 26.7394888);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (145, 'Miranda', 'Moon', NULL, 7, STR_TO_DATE
('01/01/1980', '%d/%m/%Y'), 1.30E+05, 0.0013, 68.312, 311.33, 4.338, 326.438, 254.6906576);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (146, 'Cordelia', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 4.98E+04, 0.0003, 136.827, 254.805, 0.085, 38.374, 1074.518316);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (147, 'Ophelia', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 5.38E+04, 0.0099, 17.761, 116.259, 0.104, 164.048, 956.428333);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (148, 'Bianca', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 5.92E+04, 0.0009, 8.293, 138.486, 0.193, 93.22, 828.3879607);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (149, 'Cressida', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 6.18E+04, 0.0004, 44.236, 233.795, 0.006, 99.403, 776.5824144);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (150, 'Desdemona', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 6.27E+04, 0.0001, 183.285, 184.627, 0.113, 306.089, 760.0555393);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (151, 'Juliet', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 6.44E+04, 0.0007, 223.819, 244.696, 0.065, 200.155, 730.1261349);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (152, 'Portia', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 6.61E+04, 0.0001, 222.433, 218.312, 0.059, 260.067, 701.4864814);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (153, 'Rosalind', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 6.99E+04, 0.0001, 140.477, 136.181, 0.279, 12.847, 644.6304183);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (154, 'Belinda', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 7.53E+04, 0.0001, 42.406, 357.224, 0.031, 279.337, 577.3602885);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (155, 'Puck', 'Moon', NULL, 7, STR_TO_DATE
('19/01/1986', '%d/%m/%Y'), 8.60E+04, 0.0001, 177.094, 245.796, 0.319, 268.734, 472.5445878);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (156, 'Perdita', 'Moon', NULL, 7, STR_TO_DATE
('25/04/2004', '%d/%m/%Y'), 7.64E+04, 0.0116, 253.925, 192.405, 0.47, 309.376, 564.246959);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (157, 'Mab', 'Moon', NULL, 7, STR_TO_DATE
('25/04/2004', '%d/%m/%Y'), 9.77E+04, 0.0025, 249.565, 273.769, 0.134, 350.737, 390.050107);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (158, 'Cupid', 'Moon', NULL, 7, STR_TO_DATE
('25/04/2004', '%d/%m/%Y'), 7.44E+04, 0.0013, 247.608, 163.83, 0.099, 182.793, 587.443649);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (159, 'Caliban', 'Moon', NULL, 7, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 7.23E+06, 0.1812, 354.339, 7.271, 141.529, 171.189, 0.6209758);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (160, 'Sycorax', 'Moon', NULL, 7, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.22E+07, 0.5219, 20.103, 266.583, 159.42, 263.034, 0.2794217);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (161, 'Prospero', 'Moon', NULL, 7, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.63E+07, 0.4445, 174.152, 233.586, 151.83, 319.003, 0.1819679);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (162, 'Setebos', 'Moon', NULL, 7, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.74E+07, 0.5908, 359.953, 179.449, 158.235, 250.235, 0.1617921);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (163, 'Stephano', 'Moon', NULL, 7, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 8.01E+06, 0.2248, 14.956, 270.163, 143.819, 191.411, 0.5313866);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (164, 'Trinculo', 'Moon', NULL, 7, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 8.51E+06, 0.2194, 158.688, 180.374, 166.971, 193.755, 0.4803847);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (165, 'Francisco', 'Moon', NULL, 7, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 4.28E+06, 0.1324, 140.644, 3.202, 147.25, 100.738, 1.3478663);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (166, 'Margaret', 'Moon', NULL, 7, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.41E+07, 0.6772, 90.017, 322.187, 57.367, 7.067, 0.2167366);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (167, 'Ferdinand', 'Moon', NULL, 7, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.04E+07, 0.3993, 156.298, 26.163, 169.793, 217.35, 0.1290311);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (168, 'Triton', 'Moon', NULL, 8, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 3.55E+05, 0, 66.142, 352.257, 156.865, 177.608, 61.2572638);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (169, 'Nereid', 'Moon', NULL, 8, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 5.51E+06, 0.7507, 281.117, 216.692, 7.09, 335.57, 0.9996276);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (170, 'Naiad', 'Moon', NULL, 8, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 4.82E+04, 0.0003, 2.045, 30.035, 4.691, 42.279, 1222.843585);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (171, 'Thalassa', 'Moon', NULL, 8, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 5.01E+04, 0.0002, 237.065, 262.923, 0.135, 145.98, 1155.755975);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (172, 'Despina', 'Moon', NULL, 8, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 5.25E+04, 0.0002, 176.857, 230.812, 0.068, 77.06, 1075.733067);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (173, 'Galatea', 'Moon', NULL, 8, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 6.20E+04, 0.0001, 343.011, 65.999, 0.034, 37.247, 839.661303);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (174, 'Larissa', 'Moon', NULL, 8, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 7.35E+04, 0.0014, 249.891, 166.246, 0.205, 308.127, 649.054077);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (175, 'Proteus', 'Moon', NULL, 8, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.18E+05, 0.0005, 67.968, 250.938, 0.075, 315.131, 320.7656245);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (176, 'S/2004 N 1', 'Moon', NULL, 8, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.05E+05, 0, 0, 302.652, 0, 0, 378.9061402);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (177, 'Halimede', 'Moon', NULL, 8, STR_TO_DATE
('10/01/2003', '%d/%m/%Y'), 1.67E+07, 0.2909, 162.119, 105.258, 112.898, 217.288, 0.1915578);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (178, 'Psamathe', 'Moon', NULL, 8, STR_TO_DATE
('10/01/2003', '%d/%m/%Y'), 4.67E+07, 0.4617, 144.158, 190.027, 137.679, 298.074, 0.0394359);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (179, 'Sao', 'Moon', NULL, 8, STR_TO_DATE
('10/01/2003', '%d/%m/%Y'), 2.26E+07, 0.2827, 65.047, 168.139, 49.907, 60.354, 0.123323);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (180, 'Laomedeia', 'Moon', NULL, 8, STR_TO_DATE
('10/01/2003', '%d/%m/%Y'), 2.36E+07, 0.4339, 140.107, 285.863, 34.049, 59.124, 0.1133637);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (181, 'Neso', 'Moon', NULL, 8, STR_TO_DATE
('10/01/2003', '%d/%m/%Y'), 5.03E+07, 0.4243, 86.441, 260.648, 131.265, 49.151, 0.0364349);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (182, 'Charon', 'Moon', NULL, 9, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.96E+04, 0.0002, 146.106, 131.07, 0.08, 26.928, 56.362521);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (183, 'Nix', 'Moon', NULL, 9, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 4.87E+04, 0, 324.463, 284.405, 0, 203.4, 14.4841304);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (184, 'Hydra', 'Moon', NULL, 9, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 6.47E+04, 0.0056, 153.307, 326.678, 0.304, 113.173, 9.4235386);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (185, 'Kerberos', 'Moon', NULL, 9, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 5.77E+04, 0, 160.629, 161.061, 0.426, 305.871, 11.1913026);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (186, 'Styx', 'Moon', NULL, 9, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 4.24E+04, 0.0006, 330.244, 194.546, 0.08, 26.956, 17.8551357);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (187, 'Earth Station', 'Station', NULL, 3, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 5.00E+04, 0.2, 0, 0, 0, 0, 279.5439972);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (188, 'Mars Station', 'Station', NULL, 4, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 2.00E+04, 0.2, 0, 0, 0, 0, 362.1719973);
INSERT INTO `exmachinis`.`objects` (`object_id`, `object_name`, `object_type`, `gravitational_parameter`, `central_body_object_id`, `epoch`, `semimajor_axis`, `eccentricity`, `periapsis_argument`, `mean_anomaly`, `inclination`, `ascending_node_longitude`, `mean_angular_motion`) VALUES (189, 'Jupiter Station', 'Station', NULL, 5, STR_TO_DATE
('01/01/2000', '%d/%m/%Y'), 1.00E+06, 0.2, 0, 0, 0, 0, 55.69976758);

COMMIT;

